README.md
Fixed some issues in the README file. :smile:
=> Fix spelling errors in README and link license file.

docs/example/dropdownDocs.vue
I missed this one on my previous pass through the docs.
=> Fixed typo in Dropdown that I missed.

docs/example/modalDocs.vue, src/Modal.vue
=> Added ability to override modal header and footer.

src/Typeahead.vue
unnecessary text "asdf" removed
=> Update Typeahead.vue unnecessary text "asdf" removed

src/Option.vue, src/Select.vue
selected item now show option label. (problem: http://jsfiddle.net/0Ltpdcj1/3/) https://github.com/yuche/vue-strap/issues/69
select value can be string or array,
=> selected item now show option label.

docs/example/modalDocs.vue, src/Modal.vue
This pull request includes several enhancements to modal:
A variation of Lidbetter's responsive modal pull request that will work with vue.js 1.x.
Allows null width for responsive modals.
Relational widths like '80%' or '5em' are now allowed as well.
Numeric widths will be treated as pixels.
Small and Large options to enable the modal-sm and modal-lg classes respectively.
Clean up of documentation.
=> Modal enhancements

src/Option.vue
=> Option Unused value removed

docs/example/selectDocs.vue, src/Select.vue
Fixes #90 (Select used with options and multiple==false)
=> Fixing select not updating 'selectedItems' text

docs/example/tabsDocs.vue, src/Tabset.vue
Add a prop for active tab, so that we can programmatically change the active tab.
=> Add prop for active tab

docs/example/selectDocs.vue
This pull request will add documentation for #92
=> Add documentation for the close-on-select property.

docs/example/buttonsDocs.vue, src/checkboxBtn.vue, src/radioBtn.vue
- Allow defining initial values
- Clarifying documentation
=> Checkbox & Radio Buttons

src/Select.vue
=> Select.selectedItems: make sure only strings are added to the title

docs/example/selectDocs.vue, src/Select.vue
Adds an option to disabled selectbox.
=> add disabled props to select component

docs/example/modalDocs.vue, src/Modal.vue
Added props to allow the ok and cancel buttons to display custom text.
=> Allow ok and cancel text to be custom values

docs/example/modalDocs.vue
Added the backdrop modal option mentioned [here](https://github.com/yuche/vue-strap/issues/62) to the documentation.
=> Added undocumented backdrop modal option to the docs.

src/Datepicker.vue
Hi there,
I found when I use the datepicker and open the year panel, it will not close when I click other place.
So I just fix this bug and hope it's not a feature. :smile:
=> bugfix for Datepicker close method

src/utils/EventListener.js, src/utils/callAjax.js, src/utils/coerceBoolean.js, src/utils/getScrollBarWidth.js
Change the way of importing module. When module import from src folder. the problem happens.
=> fix the token issue

docs/example/datepickerDocs.vue, src/Datepicker.vue
Hi again : here's the pull request
2 commit : 
* (try to) fix the null issue when parsing null or empty
* allow user to specify a placeholder (shown when date value is null or empty)
thanks
David
=> Fix issue 230

src/Datepicker.vue, src/translations.js
Hi
i added french translations 
i also (tried to) fix(ed) the datepicker : if someone changes the input value (either programmatically or by inputing a new value), the date selection dialog is not using the new value to reposition itself on the appropriate date
i added the same 'parse' from the ready function to inputClick which solved the case when the input is changed with the dialog closed
i'm not sure make the same work while the dialog is opened...
regards
David
=> French translations + [datepicker] sync'ing between input value and currDate state 

docs/example/carouselDocs.vue, index.html
This fixes mixed content issues while using Github Pages.
=> fix mixed content

src/Datepicker.vue
fix
when clear value,
currDate = 'Jan 1970'
=> remove null so set default date as now

src/Typeahead.vue
Add debounce to avoid fast HTTP query  (may provide function for #252)
=> Add debounce to avoid fast HTTP query  (may provide function for #252)

src/Datepicker.vue
this is a hotfix for issue #331
=> fix issue #331

src/Tabset.vue
Need to put contents of tabset into a single root element
=> Tabset needs single root element

src/Checkbox.vue
Checkboxes in  Button Group will work well with this PR.
=> fix checkbox in button group
