yuche/vue-strap

package.json
Allow projects that use browerify instead of webpack to easily `require` components
=> Declare vueify transform in package.json

src/Modal.vue
按照vuejs.org的文档，修复了在src/Modal.vue中对slot的错误使用。
尽量保持vue-strap文档中对modal的使用方式
可以如下使用：
```
<modal :show.sync="modalShown" title="modalTitle">
<div slot="modal-body">I am body</div>
<div slot="modal-footer" class="modal-footer">
<button type="button" class="btn btn-default" @click="close">Close</button>
<button type="button" class="btn btn-primary" @click="saveChange">Save changes</button>
</div>
</modal>
```
原来的bug在于：无论在<modal></modal>中写什么，都会被复制3次，原因是对`slot`的使用错误。
=> Fixed bugs while using slot in Modal

src/Slider.vue
Sets the initial index for slider to an integer instead of a string. Now the first slide gets the active class on load.
=> Fixes initial carousel render

src/Modal.vue
The show property wasn't computed at the creation of the component, so Modal.show was always treated as false.
=> Fixes Modal.show property

src/utils/getScrollBarWidth.js
e.g.
```
<template>
<button class="btn btn-primary"
@click="fadeModal = true">
Fade modal
</button>
<modal title="Fade Modal" :show.sync="fadeModal" effect="fade" :width="400">
<div slot="modal-body" class="modal-body">...</div>
</modal>
<p style="word-break: break-all;">12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890</p>
</template>
```
=> Fixed bug, when the page don't have scrollbar, calculation error in getScrollBarWidth.js.

src/Tabset.vue
Allows placing html tags inside tabs headers, i. e. an icon:
````html
<tabs>
<tab :header='"<i class=\"fa fa-user\"></i> Profile"'>
tab content
</tab>
</tabs>
````
=> Allow raw HTML in Tabs headers

src/Select.vue
I added a prop for the select component that if set to true will close the select dropdown after an option is selected. The prop is only relevant if multiple is set to false.
=> Add prop to close dropdown on selection for non multiple selects

docs/example/selectDocs.vue, src/Option.vue, src/Select.vue
- Allow defining initial values for selection
- Using scoped styles to avoid CSS selection conflicts
- Consistently using an array (with conversion of a string value to an array internally)
- Renamed CSS "placeholder" and "content" to "btn-placeholder" and "btn-content" to avoid conflicts with common CSS classes
- Coding style cleanup for consistency
- Simplification of selectedItems due to using Array consistently
- Allow closeOnSelect also for multiple selections
- Fix of CSS class bs_searchbox to bs-searchbox
=> Select & Option refactor

src/Tab.vue
This resolves an issue introduced in my last pull request to add a property for active tab.
https://github.com/yuche/vue-strap/pull/104
=> Update property name to match parent

src/Accordion.vue, src/Alert.vue, src/Aside.vue, src/Carousel.vue, src/Modal.vue, src/Panel.vue, src/Progressbar.vue, src/Select.vue, src/Tab.vue, src/Typeahead.vue, src/checkboxBtn.vue, src/popoverMixins.js, src/radioBtn.vue, src/utils/coerceBoolean.js
Allow simpler notation for Boolean attributes in markup. Instead of
(in Jade):
```jade
alert(v-bind:dismissable="true") message
```
You can now just type:
```jade
alert(dismissable="true") message
```
If the value of the property is not "true", "false", "null" or "undefined"
then it will simply be passed as-is so that Vue can throw a warning.
If the version of Vue is older than 1.0.12 then the coercion simply won't
happen and you will have to specify props using the longer notation.
I made a short example for tinkering with here: [Coerce Boolean Example][0]
[0]: http://codepen.io/sirlancelot/pen/pgqeqG?editors=1010
=> Add coercion prop option when using Vue > 1.0.12

src/Typeahead.vue
Currently the value being compared is forced to lowercase, but the query string against which it is being compared isn't. this means that matches are possible only to lowercase input (this can be seen currently on the US states example on the documentation site). This fix forces both value and query string to lowercase (for case insensitive comparisons only) allowing upper, lower and mixed case searches to match when appropriate.
=> Correction to case insensitive comparisons in typeahead

docs/example/datepickerDocs.vue, src/Datepicker.vue
Adds an option to show a reset button inside the datepickers text input field that clears the entered date. Useful for forms where the date field is optional, i.e. search forms.
=> Add reset button to datepicker component

bower.json
Bower detects and reports a difference between the semver git tag and the version in this bower.json file. One approach would be to ensure that the bower.json file is updated for each release - but that's a pain. So a better approach is simply to remove the version number from it and allow the semver git tag to be used without contradiction.
=> Bower version mismatch

src/Typeahead.vue
Commit sought to protect against a risk already mitigated by vue-strap's build process, and so achieves nothing other than adding redundant code to the dist.
=> Revert commit 7d56940

src/Panel.vue
Don't set a max-height until the panel is about to be collapsed. This allows
for the contents of the panel to grow or shrink.
May fix #87
=> Set max-height during panel transition

package.json, src/Aside.vue, src/Modal.vue, src/Panel.vue, src/Popover.vue, src/Select.vue, src/Tabset.vue, src/Tooltip.vue
TL;DR I fixed #112 #55  #28 #13 (all are same issue) correctly and issue #133  and added some slot tags where i found appropriate
I ran into  the issue yesterday and didn't like the hack original issuer ( #28  ) used. so i traced its cause and fixed it.
the problem was that vue-strap does not specify `transform: babelify` for browersify-transforms even though index,js and main,js are es6 code.
So I added the code. and it works.
Also I fixed a typo in tabSet.vue #133 
I changed ` <div class="tab-content" v-el:tabContent>` to `<div class="tab-content" v-el:tab-content>`
Other changes I did was to wrap `{{header}}`, `{{title}}` and `{{{ content}}}` in a `<slot>` tag so by default code will work as it used to, but now we can use `<slot>` to pass html around instead of using attributes.
=> Fixed issue #112 and #55 and added slot tags

package.json
require('vue-strap').modal //fails
import {modal} from 'vue-strap' //fails
require('vue-strap/src/main.js').modal //fails
require('vue-strap/src/index.js').modal // works
require('vue-strap').modal //works
import {modal} from 'vue-strap' //works
require('vue-strap/src/main.js').modal //fails
require('vue-strap/src/index.js').modal // works
The problem is two-fold
1. `main` originally pointed to `src/main.js` but was changed to `dist/vue-strap.js` to fix a problem #157 . 
according to https://github.com/yuche/vue-strap/issues/13#issuecomment-163075376
so naturally, `main` should be updated to `src/main.js` 
2. `require('vue-strap').modal` works when main refers to index.js instead of main.js. I am using laravel-elixir-vueify with browserify. imo, main.js is redundant. but I am not the one …
=> updated 'main' to point to index.js instead of dist/vue-strap.js

docs/example/datepickerDocs.vue, src/Datepicker.vue
Datepicker doesn't play nicely with the date formats dd-MM-yyyy and dd/MM/yyyy commonly used outside of North America.
The constructor for the Date class can't tell these apart from MM-dd-yyyy and MM/dd/yyyy and treats them as though they were the latter leading to some minor bugs in highlighting the active date and a ton of Vue warnings if the date chosen is later than the 12th.
This PR catches these date formats and flips them round to ensure that the Date object is instantiated correctly. The Docs have also been updated to show these formats in action.
=> Datepicker support for non-US date formats

docs/example/typeaheadDocs.vue, src/Typeahead.vue
This PR adds a "match-start" prop to allow for more intuitive matches. For example, when entering a US state with limit = 8, but match-start not set, i.e. the current default state, entering "O" will yield Arizona, California, Colorado, Connecticut, Florida, Georgia, Idaho and Illinois, which are probably not what is intended.
With the match-start prop enabled, it will match Oregon, Oklahoma and Ohio instead. Yay!
=> Allow typeahead queries to be matched strictly to suggestion starts

src/Tabset.vue
The warning in vue@1.0.17 is annoying.
fix Issue #133
=> fix(Tabset.vue): Correct the wrong use of camelCase name for "v-el:"

src/Select.vue
in `Select.vue`
`<span class="glyphicon glyphicon-ok check-mark" v-show="value.indexOf(option.value) !== -1"></span>`
will run before `ready()`, so value has not be converted to Array and also can not use `indexOf` method(maybe string can, but still a wrong way).
=> fixed TypeError: scope.value.indexOf is not a function when Select.value is a number

src/Dropdown.vue
the dropdown remained open if a **link in the dropdown** was clicked.
this fix takes care of that faulty behaviour.
=> fix: close dropdown on dropdown link click

src/utils/callAjax.js
The ajax request is parsing the result as JSON, however this isn't being set in the headers. Firefox adds default headers for text/html, text/xml etc.
This means that some frameworks like Laravel, Umbraco etc start to automatically return the data as XML, breaking the typeahead data parsing.
=> explicitly accept json in ajax requests

package.json
Revert #158  which made projects using vue-strap do a build to vue-strap, which to me is not correct. Using the dist folder means projects will use the built version of vue-strap and will not need loaders for sass or even vue.
=> Change main.js in package.json to point to the dist folder

docs/example/asideDocs.vue
While the rest of the code is correct, the code enclosed within the pre tags that is visible to the user for the Vue Strap documentation is misleading. It originally read as "sidebar", when it should have been aside.
The markup located at https://yuche.github.io/vue-strap/#aside:
```
<sidebar :show.sync="showRight" placement="right" header="Title" :width="350">
</sidebar>
```
=> Fix Aside Documentation.

src/Select.vue
hi!
I found something wrong in multiple select component, about set the selected status.
if 'value'  = 0 or = false, etc. It can't be selected. 👀 ⬇️
In 'Select.vue' file,
```html
<span class="glyphicon glyphicon-ok check-mark" v-show="isSelected(option[optionsValue] || option)"></span>
```
this `option[optionsValue] || option` will return 'option', and then.
In this method, will return false.
```js
isSelected (v) {
return this.values.indexOf(v) > -1
}
```
so! I remove the '|| option'.  Because we would not care the argument of 'indexOf()', it will automatically be 'string'.
=> fix multiple select bug

docs/example/typeaheadDocs.vue
I put the `asyncTemplate` and the `githubTemplate` code into the `doc-code` block in typeaheadDocs. The different template parameters were a bit confusing to me at first because they didn't correspond to the actual sample JS given. Hopefully this will help someone else figure things out quicker :)
=> Updated typeaheadDocs to show actual example template code

docs/example/typeaheadDocs.vue
Async typeaheads need to have an "async" property, not a "src" property. The working examples were correct, but the documented code underneath them still had it as "src".
=> Updated typeahead docs example to use async instead of src

src/Datepicker.vue
I find this behaviour is preferable to the current default. Otherwise I've had instances where people use tab to fill out a form.. and once they tab into the datepicker field since the calendar doesn't appear they start typing.. and still there is nothing to catch this unwanted behaviour or encourage the user to click on the field in order to make the picker appear. It leads to confused users and failed form submittals a plenty
=> @click -> @focus to handle keyboard users (tab)

src/Tabset.vue
`v-html` is not supposed to work on abstract tags such as `<slot>`.
=> Fix display of tabs label #520
